# Generated by Django 4.2.5 on 2023-12-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produit', '0002_commentaires'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaires',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
