# Generated by Django 4.1.1 on 2024-03-31 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produit', '0004_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='Num_table',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='nombre_personnes',
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation',
            field=models.CharField(choices=[('Ceremonie Mariage', 'Ceremonie Mariage'), ('Aniversaire', 'Aniversaire'), ('Dîner', 'Dîner')], default='Dîner', max_length=32),
        ),
    ]
