# Generated by Django 5.0.3 on 2024-04-22 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produit', '0005_commande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
