# Generated by Django 5.0.3 on 2024-04-22 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produit', '0006_alter_commande_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commande',
            options={'verbose_name': 'Commande', 'verbose_name_plural': 'Commandes'},
        ),
    ]
