# Generated by Django 4.1.1 on 2024-04-01 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produit', '0006_remove_reservation_plats_commandes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='note',
        ),
    ]
