# Generated by Django 5.0.3 on 2024-04-22 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produit', '0007_alter_commande_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentaires',
            options={'verbose_name': 'Commentaire', 'verbose_name_plural': 'Commentaires'},
        ),
    ]
