# Generated by Django 4.1.1 on 2024-04-01 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produit', '0008_reservation_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation',
            field=models.CharField(choices=[('Ceremonie Mariage', 'Ceremonie Mariage'), ('Aniversaire', 'Aniversaire'), ('Dîner', 'Dîner')], default='Dîner', max_length=32),
        ),
    ]
