# Generated by Django 5.0.3 on 2024-04-23 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produit', '0008_alter_commentaires_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='orders',
        ),
        migrations.AddField(
            model_name='commande',
            name='nom',
            field=models.CharField(default='salut', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commande',
            name='qte',
            field=models.IntegerField(default=1),
        ),
    ]
