# Generated by Django 5.0.3 on 2024-04-23 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produit', '0010_commandes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='user',
        ),
        migrations.AlterField(
            model_name='commandes',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
