# Generated by Django 5.0.3 on 2024-04-23 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produit', '0011_remove_commande_user_alter_commandes_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commande',
            name='date_comande',
        ),
        migrations.AddField(
            model_name='commandes',
            name='date_comande',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
