# Generated by Django 5.0.3 on 2024-04-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_produit', '0014_usercommande_remove_commandes_date_comande_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercommande',
            name='date_comande',
        ),
        migrations.AddField(
            model_name='commandes',
            name='date_comande',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
