# Generated by Django 4.2.5 on 2023-12-01 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_compte', '0002_utilisateurs_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateurs',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
