# Generated by Django 5.0.1 on 2024-02-14 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_compte', '0003_alter_utilisateurs_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateurs',
            name='token',
            field=models.CharField(default='', max_length=120),
        ),
    ]
